"""
将指标库内存数据迁移到 Supabase
运行方式: python scripts/migrate_indicator_data.py
"""

import sys
sys.path.insert(0, 'web/backend')

import logging
from services.supabase_service import SupabaseService

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# 内存中的原始数据（从 indicator_report.py 移出的 INDICATOR_DATABASE）
INDICATOR_DATABASE = [
    {
        "name": "龙湖天街商业综合体",
        "category": "商业",
        "location": "北京",
        "structure": "框架结构",
        "floor_above": 6,
        "floor_below": 2,
        "area_total": 150000,
        "area_above": 110000,
        "area_below": 40000,
        "height": 35,
        "complete_date": "2025-06",
        "source": "结算文件",
        "total_cost": 45000,
        "unit_cost": 3000,
        "unit_structure": 1800,
        "unit_installation": 600,
        "unit_decoration": 500,
        "unit_measure": 100,
        "steel": 55,
        "concrete": 0.45,
        "formwork": 2.5,
        "block": 0.15,
        "cable": 0.08,
        "pipe": 0.15,
        "underground_structure": 450,
        "above_structure": 600,
        "roof": 50,
        "exterior_wall": 200,
        "interior_wall": 150,
        "floor": 120,
        "electrical": 250,
        "plumbing": 150,
        "hvac": 200,
        "elevator": 80,
        "fire": 100,
        "measures": 100,
        "verified": True,
        "verified_by": "管理员",
    },
    {
        "name": "万达广场购物中心",
        "category": "商业",
        "location": "北京",
        "structure": "框架结构",
        "floor_above": 5,
        "floor_below": 2,
        "area_total": 180000,
        "area_above": 130000,
        "area_below": 50000,
        "height": 32,
        "complete_date": "2025-03",
        "source": "结算文件",
        "total_cost": 57600,
        "unit_cost": 3200,
        "unit_structure": 1900,
        "unit_installation": 650,
        "unit_decoration": 550,
        "unit_measure": 100,
        "steel": 58,
        "concrete": 0.48,
        "formwork": 2.6,
        "verified": True,
        "verified_by": "管理员",
    },
    {
        "name": "万科翡翠公园住宅",
        "category": "住宅",
        "location": "北京",
        "structure": "剪力墙结构",
        "floor_above": 28,
        "floor_below": 2,
        "area_total": 85000,
        "area_above": 75000,
        "area_below": 10000,
        "height": 85,
        "complete_date": "2025-05",
        "source": "结算文件",
        "total_cost": 23800,
        "unit_cost": 2800,
        "unit_structure": 1700,
        "unit_installation": 550,
        "unit_decoration": 450,
        "unit_measure": 100,
        "steel": 52,
        "concrete": 0.42,
        "formwork": 2.2,
        "block": 0.12,
        "underground_structure": 300,
        "above_structure": 800,
        "roof": 40,
        "exterior_wall": 150,
        "interior_wall": 200,
        "floor": 180,
        "electrical": 200,
        "plumbing": 120,
        "hvac": 150,
        "fire": 80,
        "measures": 80,
        "verified": True,
        "verified_by": "管理员",
    },
    {
        "name": "国贸CBD写字楼",
        "category": "办公",
        "location": "北京",
        "structure": "框架核心筒",
        "floor_above": 35,
        "floor_below": 4,
        "area_total": 120000,
        "area_above": 100000,
        "area_below": 20000,
        "height": 150,
        "complete_date": "2025-01",
        "source": "结算文件",
        "total_cost": 54000,
        "unit_cost": 4500,
        "unit_structure": 2500,
        "unit_installation": 900,
        "unit_decoration": 800,
        "unit_measure": 300,
        "steel": 75,
        "concrete": 0.55,
        "formwork": 2.8,
        "cable": 0.15,
        "duct": 0.08,
        "verified": True,
        "verified_by": "管理员",
    },
    {
        "name": "烟台万达广场",
        "category": "商业",
        "location": "山东",
        "structure": "框架结构",
        "floor_above": 5,
        "floor_below": 1,
        "area_total": 95000,
        "area_above": 80000,
        "area_below": 15000,
        "height": 28,
        "complete_date": "2025-02",
        "source": "结算文件",
        "total_cost": 24700,
        "unit_cost": 2600,
        "unit_structure": 1550,
        "unit_installation": 520,
        "unit_decoration": 430,
        "unit_measure": 100,
        "steel": 48,
        "concrete": 0.40,
        "formwork": 2.3,
        "verified": True,
        "verified_by": "管理员",
    },
    {
        "name": "烟台万科城住宅",
        "category": "住宅",
        "location": "山东",
        "structure": "剪力墙结构",
        "floor_above": 18,
        "floor_below": 1,
        "area_total": 65000,
        "area_above": 58000,
        "area_below": 7000,
        "height": 55,
        "complete_date": "2025-04",
        "source": "结算文件",
        "total_cost": 15600,
        "unit_cost": 2400,
        "unit_structure": 1450,
        "unit_installation": 480,
        "unit_decoration": 380,
        "unit_measure": 90,
        "steel": 45,
        "concrete": 0.38,
        "formwork": 2.0,
        "block": 0.10,
        "underground_structure": 250,
        "above_structure": 700,
        "roof": 35,
        "exterior_wall": 130,
        "interior_wall": 170,
        "floor": 150,
        "electrical": 180,
        "plumbing": 100,
        "hvac": 120,
        "fire": 70,
        "measures": 75,
        "verified": True,
        "verified_by": "管理员",
    },
    {
        "name": "龙湖天琅住宅",
        "category": "住宅",
        "location": "北京",
        "structure": "剪力墙结构",
        "floor_above": 32,
        "floor_below": 2,
        "area_total": 95000,
        "area_above": 85000,
        "area_below": 10000,
        "height": 98,
        "complete_date": "2025-05",
        "source": "结算文件",
        "total_cost": 29350,
        "unit_cost": 3089,
        "unit_structure": 1850,
        "unit_installation": 600,
        "unit_decoration": 500,
        "unit_measure": 139,
        "steel": 60,
        "concrete": 0.48,
        "formwork": 2.4,
        "verified": True,
        "verified_by": "管理员",
    },
    {
        "name": "济南恒隆广场",
        "category": "商业",
        "location": "山东",
        "structure": "框架结构",
        "floor_above": 7,
        "floor_below": 2,
        "area_total": 120000,
        "area_above": 95000,
        "area_below": 25000,
        "height": 40,
        "complete_date": "2025-06",
        "source": "结算文件",
        "total_cost": 28800,
        "unit_cost": 2400,
        "unit_structure": 1440,
        "unit_installation": 480,
        "unit_decoration": 380,
        "unit_measure": 100,
        "steel": 45,
        "concrete": 0.38,
        "formwork": 2.2,
        "verified": True,
        "verified_by": "管理员",
    },
]


def migrate():
    """执行迁移"""
    logger.info(f"[migrate] 开始迁移指标库数据 | 总数={len(INDICATOR_DATABASE)}")

    supabase = SupabaseService()
    result = supabase.import_indicator_projects(INDICATOR_DATABASE)

    logger.info(f"[migrate] 迁移完成 | 成功={result['imported']}, 总数={result['total']}")

    if result['errors']:
        logger.warning(f"[migrate] 失败记录: {result['errors']}")
    else:
        logger.info(f"[migrate] 所有数据迁移成功！")

    return result


if __name__ == "__main__":
    migrate()